Some eror
ImportError: cannot import name 'get_ydl_opts_with_cookies' from 'utils.ydl_opts' (C:\Users\Pilif\AppData\Local\Temp\_MEI278442\utils\ydl_opts.pyc)
[PYI-29404:ERROR] Failed to execute script 'main' due to unhandled exception!